# Site settings
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.jennylam.cc" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
encoding: UTF-8

kramdown:
    syntax_highlighter: Null

# Collections
collections:
   courses:
    output: true

# Trick to use newlines in Liquid Templates
newline: "\n"

sass:
  style: compressed

# About me!
name: Jenny Lam
title: Assistant Professor
department: Department of Computer Science
school: San Jos&eacute; State University
img: assets/img/picture_s.jpg
