# Site settings
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.jennylam.cc" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
encoding: UTF-8

kramdown:
    input: GFM
    syntax_highlighter: rouge
    # hard_wrap: false

    # Rouge Highlighter in Kramdown › http://kramdown.gettalong.org/syntax_highlighter/rouge.html
    # span, block element options fall back to global
    syntax_highlighter_opts:
      # Rouge Options › https://github.com/jneen/rouge#full-options
      css_class: 'highlight'
      #line_numbers: true # bad idea, spans don't need linenos and would inherit this option
      # span:
      #   line_numbers: false
      # block:
      #   line_numbers: true
      #   start_line: 1

# Collections
collections:
   courses:
    output: true

# Trick to use newlines in Liquid Templates
newline: "\n"

sass:
  style: compressed

# About me!
name: Jenny Lam
title: Assistant Professor
department: Department of Computer Science
school: San Jos&eacute; State University
img: assets/img/picture_s.jpg

link: jenny.lam01@sjsu.edu
